# Generated by Django 2.2.24 on 2021-10-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_choices_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
