# Generated by Django 2.2.24 on 2021-10-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211006_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_many',
            field=models.BooleanField(default=False, verbose_name='Allow Many Choices'),
        ),
    ]
