# Generated by Django 2.2.24 on 2021-10-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_class_exercise_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('position',), 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
    ]
