# Generated by Django 2.2.24 on 2021-10-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211007_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='number_of_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='number_of_exercises',
            field=models.IntegerField(default=0),
        ),
    ]
