# Generated by Django 2.2.24 on 2021-10-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_classstatus_exercisestatus'),
        ('home', '0009_auto_20211007_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='clients',
            field=models.ManyToManyField(through='users.ClassStatus', to='users.Client'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='clients',
            field=models.ManyToManyField(through='users.ExerciseStatus', to='users.Client'),
        ),
    ]
