# Generated by Django 2.2.24 on 2021-10-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211010_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Series'),
            preserve_default=False,
        ),
    ]
