# Generated by Django 2.2.24 on 2021-10-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211010_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitToStandVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='sittostand/video/')),
            ],
        ),
    ]
