# Generated by Django 2.2.24 on 2021-10-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_sittostandvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['position'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['position'], 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position'], 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='class',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Presentation Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Presentation Order'),
            preserve_default=False,
        ),
    ]
