# Generated by Django 2.2.24 on 2021-10-11 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211011_2044'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('series', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('series', 'position')},
        ),
    ]
