# Generated by Django 2.2.24 on 2021-10-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211011_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Series'),
        ),
    ]
