# Generated by Django 2.2.24 on 2022-01-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211028_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongradulatoryMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Textual Content of Message')),
            ],
        ),
    ]
