# Generated by Django 2.2.24 on 2022-01-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_adminemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['week_number', 'day_number'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['week_number', 'day_number'], 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AddField(
            model_name='class',
            name='day_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='week_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='day_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='week_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
