# Generated by Django 2.2.24 on 2022-01-13 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20220112_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.RemoveField(
            model_name='series',
            name='position',
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='class',
            name='position',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='position',
        ),
    ]
