# Generated by Django 2.2.24 on 2022-01-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220113_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='additional_resource',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='additional_resource',
            field=models.URLField(blank=True, null=True),
        ),
    ]
