# Generated by Django 2.2.27 on 2022-02-11 08:40

from django.db import migrations
import s3upload.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20220125_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='video_url',
            field=s3upload.fields.S3UploadField(blank=True, dest='destination', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=s3upload.fields.S3UploadField(blank=True, dest='destination', null=True),
        ),
    ]
