# Generated by Django 2.2.27 on 2022-02-11 18:51

from django.db import migrations
import s3upload.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20220211_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='class',
            name='video',
            field=s3upload.fields.S3UploadField(dest='destination'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=s3upload.fields.S3UploadField(dest='destination'),
        ),
    ]
