# Generated by Django 2.2.27 on 2022-02-15 04:22

from django.db import migrations
import s3upload.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20220211_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sittostandvideo',
            name='video',
            field=s3upload.fields.S3UploadField(default='www.youtube.com/file.mp4', dest='destination'),
            preserve_default=False,
        ),
    ]
