// auth types
export const SET_AUTH_MODAL = "SET_AUTH_MODAL";
export const SET_AUTH_USER_NAME = "SET_AUTH_USER_NAME";
export const SET_AUTH_USER_FIRSTNAME = "SET_AUTH_USER_FIRSTNAME";
export const SET_AUTH_USER_LASTNAME = "SET_AUTH_USER_LASTNAME";
export const SET_AUTH_EMAIL = "SET_AUTH_EMAIL";
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const SET_AUTH_IMAGE = "SET_AUTH_IMAGE";
export const SET_AUTH_DATA = "SET_AUTH_DATA";

export const SET_THREAD = "SET_THREAD";



// LOADER TYPE
export const LOADER = "LOADER";
export const CATEGORY_LOADER = "CATEGORY_LOADER";

