# Generated by Django 2.2.24 on 2021-10-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211005_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(blank=True, null=True, verbose_name='One Time Password'),
        ),
    ]
