# Generated by Django 2.2.24 on 2021-10-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='# of OTP Attempts'),
        ),
    ]
