# Generated by Django 2.2.24 on 2021-10-05 21:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), default=list, size=None),
        ),
    ]
