# Generated by Django 2.2.24 on 2021-10-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_choices_question'),
        ('users', '0007_client_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='answers',
        ),
        migrations.AddField(
            model_name='client',
            name='selections',
            field=models.ManyToManyField(blank=True, related_name='selections', to='home.Choices'),
        ),
    ]
