# Generated by Django 2.2.24 on 2021-10-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211007_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='client/images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sts_2_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sit-To-Stand #2 Date'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sts_3_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sit-To-Stand #3 Date'),
        ),
    ]
