# Generated by Django 2.2.24 on 2021-10-07 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211007_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='program_end',
            field=models.DateField(blank=True, null=True, verbose_name='Program End Date'),
        ),
        migrations.AddField(
            model_name='client',
            name='program_start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Program Start Date'),
            preserve_default=False,
        ),
    ]
