# Generated by Django 2.2.24 on 2021-10-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_class_exercise_series'),
        ('users', '0011_auto_20211007_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='series', to='home.Series'),
        ),
    ]
