# Generated by Django 2.2.24 on 2021-10-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211010_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='selections',
        ),
    ]
