# Generated by Django 2.2.24 on 2021-10-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_client_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitToStandVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='sittostand/video/')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
