# Generated by Django 2.2.24 on 2021-10-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_sittostandvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sittostandvideo',
            name='count',
        ),
    ]
