# Generated by Django 2.2.24 on 2021-10-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_delete_sittostandvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisestatus',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
