# Generated by Django 2.2.24 on 2021-10-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_exercisestatus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstatus',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
