# Generated by Django 2.2.24 on 2021-10-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_professional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='referral_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
