# Generated by Django 2.2.24 on 2021-10-13 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_professional_referral_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classstatus',
            options={'ordering': ['date'], 'verbose_name': 'Client Class', 'verbose_name_plural': 'Client Classes'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='exercisestatus',
            options={'ordering': ['date'], 'verbose_name': 'Client Exercise', 'verbose_name_plural': 'Client Exercises'},
        ),
        migrations.AlterModelOptions(
            name='professional',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Professionals'},
        ),
        migrations.AlterField(
            model_name='classstatus',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_status', to='users.Client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='classstatus',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_status', to='home.Class', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='exercisestatus',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_status', to='users.Client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='exercisestatus',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_status', to='home.Exercise', verbose_name='exercise'),
        ),
    ]
