# Generated by Django 2.2.24 on 2022-01-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20211206_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='target_heart_rate',
            new_name='maximum_heart_rate',
        ),
    ]
