# Generated by Django 2.2.24 on 2022-01-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220112_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='maximum_range_heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='minimum_range_heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
