# Generated by Django 2.2.24 on 2022-01-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20220112_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='maximum_heart_rate',
        ),
        migrations.RemoveField(
            model_name='client',
            name='maximum_range_heart_rate',
        ),
        migrations.RemoveField(
            model_name='client',
            name='minimum_range_heart_rate',
        ),
    ]
