# Generated by Django 2.2.24 on 2022-01-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20220112_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstatus',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('This was easy', 'This was easy'), ('This was okay', 'This was okay'), ('This was tough', 'This was tough')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exercisestatus',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('This was easy', 'This was easy'), ('This was okay', 'This was okay'), ('This was tough', 'This was tough')], max_length=64, null=True),
        ),
    ]
