# Generated by Django 2.2.24 on 2022-01-12 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20220112_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='users.Professional'),
        ),
    ]
