# Generated by Django 2.2.24 on 2022-01-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20220112_1211'),
        ('users', '0033_auto_20220112_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='final_checkpoint_choices',
            field=models.ManyToManyField(blank=True, related_name='third_questionnaire', to='home.Choice'),
        ),
        migrations.AddField(
            model_name='client',
            name='halfway_checkpoint_choices',
            field=models.ManyToManyField(blank=True, related_name='second_questionnaire', to='home.Choice'),
        ),
    ]
