# Generated by Django 2.2.24 on 2022-01-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20220112_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remember_me',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
